apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: twelve-clouds
spec:
  selector:
    matchLabels:
      app: twelve-clouds
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: twelve-clouds
        prometheus.io/scrape: "true"
        prometheus.io.port: "8080"
    spec:
      containers:
      - name: twelve-clouds
        image: karthequian/prom:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: twelve-clouds-service
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  ports:
  - name: http
    nodePort: 30010
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: twelve-clouds